(** UConn CSE 4102 **)
(** Spring 2026 **)
(** Homework 0 **)

(* Your name *)
let my_name = "(your name here)"

exception Unimplemented

(* True-false questions *)
(* Static types are checked at compile time *)
let q1 = raise Unimplemented
(* There are more than 4 language paradigms *)
let q2 = raise Unimplemented
(* An interpreter translates a high-level program to machine code *)
let q3 = raise Unimplemented
(* The first compiler was written by Alan Turing *)
let q4 = raise Unimplemented
(* It's possible to use ideas from one PL in another *)
let q5 = raise Unimplemented


(* Do not modify below *)
let ch = open_out "hw0_out"
let _ = Printf.fprintf ch "Generated by %s\n" Sys.executable_name
let _ = if !Sys.interactive then Printf.fprintf ch "(interactive)\n\n"
        else Printf.fprintf ch "(non-interactive)\n\n"
let _ = Printf.fprintf ch "Name: %s\n" my_name

let _ = Printf.fprintf ch "My answers to the T/F questions:\n%s\n"
          (String.concat "\n"
             (List.map string_of_bool [q1; q2; q3; q4; q5]))

let _ = Printf.fprintf ch "OS: %s \n" Sys.os_type
let _ = close_out ch
